name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  lint:
    name: Run PHP linter validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: firehed/lint-php-action@v1

  test:
    name: Test with PHP ${{ matrix.version.php }}, MySQL ${{ matrix.version.mysql }}, client ${{ matrix.client }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        client:
          - mysql
        version:
          - mysql: "5.7"
            php: "5.6"
          - mysql: "8.0"
            php: "7.4"
          - mysql: "8.0"
            php: "8.1"

    services:
      mysql:
        image: mysql:${{ matrix.version.mysql }}
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: redmap
          MYSQL_ROOT_PASSWORD: ""

    steps:
      - uses: actions/checkout@v6
      - name: Install PPA repository
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Update package sources
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install php${{ matrix.version.php }}-cli php${{ matrix.version.php }}-mysql
      - name: Run test suite
        run: php -d zend.assertions=1 test/index.php client=${{ matrix.client }}

  validate:
    name: Validate
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    steps:
      - run: true
